2024-10-29 09:36:00,038 WARNING utils.__init__: KrnlException: HTTP error: 502 Bad Gateway: 
502 Bad Gateway

502 Bad Gateway
nginx


Traceback (most recent call last):
  File "C:\Users\sam37279\AppData\Local\anaconda3\Lib\site-packages\sparqlkernel\connection.py", line 437, in query
    res = self.srv.query()
          ^^^^^^^^^^^^^^^^
  File "C:\Users\sam37279\AppData\Local\anaconda3\Lib\site-packages\SPARQLWrapper\Wrapper.py", line 960, in query
    return QueryResult(self._query())
                       ^^^^^^^^^^^^^
  File "C:\Users\sam37279\AppData\Local\anaconda3\Lib\site-packages\SPARQLWrapper\Wrapper.py", line 940, in _query
    raise e
  File "C:\Users\sam37279\AppData\Local\anaconda3\Lib\site-packages\SPARQLWrapper\Wrapper.py", line 926, in _query
    response = urlopener(request)
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\sam37279\AppData\Local\anaconda3\Lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sam37279\AppData\Local\anaconda3\Lib\urllib\request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sam37279\AppData\Local\anaconda3\Lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\sam37279\AppData\Local\anaconda3\Lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sam37279\AppData\Local\anaconda3\Lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\sam37279\AppData\Local\anaconda3\Lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
